# Generated by Django 3.1.2 on 2021-04-27 15:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='students',
            managers=[
                ('stuobj2', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='grades',
            name='gdata',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='grades',
            table='grades',
        ),
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
