# Generated by Django 3.1.2 on 2021-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210427_1506'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='students',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='lastTime',
            field=models.DateField(auto_now=True),
        ),
    ]
