# Generated by Django 3.1.2 on 2021-05-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210427_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='CreateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='lastTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
