# Generated by Django 3.1.2 on 2021-05-21 06:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210505_1539'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='students',
            managers=[
                ('stuobj', django.db.models.manager.Manager()),
            ],
        ),
    ]
